name: Notify the team on deployments

on:
    deployment_status: 

jobs:
    Pending:
        runs-on: [ubuntu-latest]
        if: github.event.deployment_status.state == 'pending'
        steps:
            - name: Notify
              run: echo pending
    InProcess:
        runs-on: [ubuntu-latest]
        if: github.event.deployment_status.state == 'in_progress'
        steps:
            - name: Notify
              run: echo in_progress
    Success:
        runs-on: [ubuntu-latest]
        if: github.event.deployment_status.state == 'success'
        steps:
            - name: Notify
              run: echo success
    Failure:
        runs-on: [ubuntu-latest]
        if: github.event.deployment_status.state == 'failure'
        steps:
            - name: Notify
              run: echo failure